##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.4.0-B60] date: [Thu Jul 18 04:24:32 PDT 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Ux_Host_MSC


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/app_threadx.c \
Core/Src/stm32l4xx_it.c \
Core/Src/stm32l4xx_hal_msp.c \
Core/Src/stm32l4xx_hal_timebase_tim.c \
USBX/App/ux_host_msc.c \
USBX/App/app_usbx_host.c \
AZURE_RTOS/App/app_azure_rtos.c \
FileX/App/app_filex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_hcd.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usb.c \
Core/Src/system_stm32l4xx.c \
Middlewares/ST/filex/common/src/fx_directory_attributes_read.c \
Middlewares/ST/filex/common/src/fx_directory_attributes_set.c \
Middlewares/ST/filex/common/src/fx_directory_create.c \
Middlewares/ST/filex/common/src/fx_directory_default_get.c \
Middlewares/ST/filex/common/src/fx_directory_default_get_copy.c \
Middlewares/ST/filex/common/src/fx_directory_default_set.c \
Middlewares/ST/filex/common/src/fx_directory_delete.c \
Middlewares/ST/filex/common/src/fx_directory_entry_read.c \
Middlewares/ST/filex/common/src/fx_directory_entry_write.c \
Middlewares/ST/filex/common/src/fx_directory_exFAT_entry_read.c \
Middlewares/ST/filex/common/src/fx_directory_exFAT_entry_write.c \
Middlewares/ST/filex/common/src/fx_directory_exFAT_free_search.c \
Middlewares/ST/filex/common/src/fx_directory_exFAT_unicode_entry_write.c \
Middlewares/ST/filex/common/src/fx_directory_first_entry_find.c \
Middlewares/ST/filex/common/src/fx_directory_first_full_entry_find.c \
Middlewares/ST/filex/common/src/fx_directory_free_search.c \
Middlewares/ST/filex/common/src/fx_directory_information_get.c \
Middlewares/ST/filex/common/src/fx_directory_local_path_clear.c \
Middlewares/ST/filex/common/src/fx_directory_local_path_get.c \
Middlewares/ST/filex/common/src/fx_directory_local_path_get_copy.c \
Middlewares/ST/filex/common/src/fx_directory_local_path_restore.c \
Middlewares/ST/filex/common/src/fx_directory_local_path_set.c \
Middlewares/ST/filex/common/src/fx_directory_long_name_get.c \
Middlewares/ST/filex/common/src/fx_directory_long_name_get_extended.c \
Middlewares/ST/filex/common/src/fx_directory_name_extract.c \
Middlewares/ST/filex/common/src/fx_directory_name_test.c \
Middlewares/ST/filex/common/src/fx_directory_next_entry_find.c \
Middlewares/ST/filex/common/src/fx_directory_next_full_entry_find.c \
Middlewares/ST/filex/common/src/fx_directory_rename.c \
Middlewares/ST/filex/common/src/fx_directory_search.c \
Middlewares/ST/filex/common/src/fx_directory_short_name_get.c \
Middlewares/ST/filex/common/src/fx_directory_short_name_get_extended.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_add_bitmap_log.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_add_checksum_log.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_add_dir_log.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_add_FAT_log.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_apply_logs.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_calculate_checksum.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_cleanup_FAT_chain.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_create_log_file.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_enable.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_read_directory_sector.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_read_FAT.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_read_log_file.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_recover.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_reset_log_file.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_set_FAT_chain.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_transaction_end.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_transaction_fail.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_transaction_start.c \
Middlewares/ST/filex/common/src/fx_fault_tolerant_write_log_file.c \
Middlewares/ST/filex/common/src/fx_file_allocate.c \
Middlewares/ST/filex/common/src/fx_file_attributes_read.c \
Middlewares/ST/filex/common/src/fx_file_attributes_set.c \
Middlewares/ST/filex/common/src/fx_file_best_effort_allocate.c \
Middlewares/ST/filex/common/src/fx_file_close.c \
Middlewares/ST/filex/common/src/fx_file_create.c \
Middlewares/ST/filex/common/src/fx_file_date_time_set.c \
Middlewares/ST/filex/common/src/fx_file_delete.c \
Middlewares/ST/filex/common/src/fx_file_extended_allocate.c \
Middlewares/ST/filex/common/src/fx_file_extended_best_effort_allocate.c \
Middlewares/ST/filex/common/src/fx_file_extended_relative_seek.c \
Middlewares/ST/filex/common/src/fx_file_extended_seek.c \
Middlewares/ST/filex/common/src/fx_file_extended_truncate.c \
Middlewares/ST/filex/common/src/fx_file_extended_truncate_release.c \
Middlewares/ST/filex/common/src/fx_file_open.c \
Middlewares/ST/filex/common/src/fx_file_read.c \
Middlewares/ST/filex/common/src/fx_file_relative_seek.c \
Middlewares/ST/filex/common/src/fx_file_rename.c \
Middlewares/ST/filex/common/src/fx_file_seek.c \
Middlewares/ST/filex/common/src/fx_file_truncate.c \
Middlewares/ST/filex/common/src/fx_file_truncate_release.c \
Middlewares/ST/filex/common/src/fx_file_write.c \
Middlewares/ST/filex/common/src/fx_file_write_notify_set.c \
Middlewares/ST/filex/common/src/fx_media_abort.c \
Middlewares/ST/filex/common/src/fx_media_boot_info_extract.c \
Middlewares/ST/filex/common/src/fx_media_cache_invalidate.c \
Middlewares/ST/filex/common/src/fx_media_check.c \
Middlewares/ST/filex/common/src/fx_media_check_FAT_chain_check.c \
Middlewares/ST/filex/common/src/fx_media_check_lost_cluster_check.c \
Middlewares/ST/filex/common/src/fx_media_close.c \
Middlewares/ST/filex/common/src/fx_media_close_notify_set.c \
Middlewares/ST/filex/common/src/fx_media_exFAT_format.c \
Middlewares/ST/filex/common/src/fx_media_extended_space_available.c \
Middlewares/ST/filex/common/src/fx_media_flush.c \
Middlewares/ST/filex/common/src/fx_media_format.c \
Middlewares/ST/filex/common/src/fx_media_format_oem_name_set.c \
Middlewares/ST/filex/common/src/fx_media_format_type_set.c \
Middlewares/ST/filex/common/src/fx_media_format_volume_id_set.c \
Middlewares/ST/filex/common/src/fx_media_open.c \
Middlewares/ST/filex/common/src/fx_media_open_notify_set.c \
Middlewares/ST/filex/common/src/fx_media_read.c \
Middlewares/ST/filex/common/src/fx_media_space_available.c \
Middlewares/ST/filex/common/src/fx_media_volume_get.c \
Middlewares/ST/filex/common/src/fx_media_volume_get_extended.c \
Middlewares/ST/filex/common/src/fx_media_volume_set.c \
Middlewares/ST/filex/common/src/fx_media_write.c \
Middlewares/ST/filex/common/src/fx_partition_offset_calculate.c \
Middlewares/ST/filex/common/src/fx_system_date_get.c \
Middlewares/ST/filex/common/src/fx_system_date_set.c \
Middlewares/ST/filex/common/src/fx_system_initialize.c \
Middlewares/ST/filex/common/src/fx_system_time_get.c \
Middlewares/ST/filex/common/src/fx_system_time_set.c \
Middlewares/ST/filex/common/src/fx_system_timer_entry.c \
Middlewares/ST/filex/common/src/fx_unicode_directory_create.c \
Middlewares/ST/filex/common/src/fx_unicode_directory_entry_change.c \
Middlewares/ST/filex/common/src/fx_unicode_directory_entry_read.c \
Middlewares/ST/filex/common/src/fx_unicode_directory_rename.c \
Middlewares/ST/filex/common/src/fx_unicode_directory_search.c \
Middlewares/ST/filex/common/src/fx_unicode_file_create.c \
Middlewares/ST/filex/common/src/fx_unicode_file_rename.c \
Middlewares/ST/filex/common/src/fx_unicode_length_get.c \
Middlewares/ST/filex/common/src/fx_unicode_length_get_extended.c \
Middlewares/ST/filex/common/src/fx_unicode_name_get.c \
Middlewares/ST/filex/common/src/fx_unicode_name_get_extended.c \
Middlewares/ST/filex/common/src/fx_unicode_short_name_get.c \
Middlewares/ST/filex/common/src/fx_unicode_short_name_get_extended.c \
Middlewares/ST/filex/common/src/fx_utility_16_unsigned_read.c \
Middlewares/ST/filex/common/src/fx_utility_16_unsigned_write.c \
Middlewares/ST/filex/common/src/fx_utility_32_unsigned_read.c \
Middlewares/ST/filex/common/src/fx_utility_32_unsigned_write.c \
Middlewares/ST/filex/common/src/fx_utility_64_unsigned_read.c \
Middlewares/ST/filex/common/src/fx_utility_64_unsigned_write.c \
Middlewares/ST/filex/common/src/fx_utility_absolute_path_get.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_allocate_new_cluster.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_bitmap_cache_prepare.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_bitmap_cache_update.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_bitmap_flush.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_bitmap_free_cluster_find.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_bitmap_initialize.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_bitmap_start_sector_get.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_cluster_free.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_cluster_state_get.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_cluster_state_set.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_geometry_check.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_name_hash_get.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_size_calculate.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_system_area_checksum_verify.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_system_area_checksum_write.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_system_area_format.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_system_sector_write.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_unicode_name_hash_get.c \
Middlewares/ST/filex/common/src/fx_utility_exFAT_upcase_table.c \
Middlewares/ST/filex/common/src/fx_utility_FAT_entry_read.c \
Middlewares/ST/filex/common/src/fx_utility_FAT_entry_write.c \
Middlewares/ST/filex/common/src/fx_utility_FAT_flush.c \
Middlewares/ST/filex/common/src/fx_utility_FAT_map_flush.c \
Middlewares/ST/filex/common/src/fx_utility_FAT_sector_get.c \
Middlewares/ST/filex/common/src/fx_utility_logical_sector_cache_entry_read.c \
Middlewares/ST/filex/common/src/fx_utility_logical_sector_flush.c \
Middlewares/ST/filex/common/src/fx_utility_logical_sector_read.c \
Middlewares/ST/filex/common/src/fx_utility_logical_sector_write.c \
Middlewares/ST/filex/common/src/fx_utility_memory_copy.c \
Middlewares/ST/filex/common/src/fx_utility_memory_set.c \
Middlewares/ST/filex/common/src/fx_utility_string_length_get.c \
Middlewares/ST/filex/common/src/fx_utility_token_length_get.c \
Middlewares/ST/filex/common/src/fxe_directory_attributes_read.c \
Middlewares/ST/filex/common/src/fxe_directory_attributes_set.c \
Middlewares/ST/filex/common/src/fxe_directory_create.c \
Middlewares/ST/filex/common/src/fxe_directory_default_get.c \
Middlewares/ST/filex/common/src/fxe_directory_default_get_copy.c \
Middlewares/ST/filex/common/src/fxe_directory_default_set.c \
Middlewares/ST/filex/common/src/fxe_directory_delete.c \
Middlewares/ST/filex/common/src/fxe_directory_first_entry_find.c \
Middlewares/ST/filex/common/src/fxe_directory_first_full_entry_find.c \
Middlewares/ST/filex/common/src/fxe_directory_information_get.c \
Middlewares/ST/filex/common/src/fxe_directory_local_path_clear.c \
Middlewares/ST/filex/common/src/fxe_directory_local_path_get.c \
Middlewares/ST/filex/common/src/fxe_directory_local_path_get_copy.c \
Middlewares/ST/filex/common/src/fxe_directory_local_path_restore.c \
Middlewares/ST/filex/common/src/fxe_directory_local_path_set.c \
Middlewares/ST/filex/common/src/fxe_directory_long_name_get.c \
Middlewares/ST/filex/common/src/fxe_directory_long_name_get_extended.c \
Middlewares/ST/filex/common/src/fxe_directory_name_test.c \
Middlewares/ST/filex/common/src/fxe_directory_next_entry_find.c \
Middlewares/ST/filex/common/src/fxe_directory_next_full_entry_find.c \
Middlewares/ST/filex/common/src/fxe_directory_rename.c \
Middlewares/ST/filex/common/src/fxe_directory_short_name_get.c \
Middlewares/ST/filex/common/src/fxe_directory_short_name_get_extended.c \
Middlewares/ST/filex/common/src/fxe_fault_tolerant_enable.c \
Middlewares/ST/filex/common/src/fxe_file_allocate.c \
Middlewares/ST/filex/common/src/fxe_file_attributes_read.c \
Middlewares/ST/filex/common/src/fxe_file_attributes_set.c \
Middlewares/ST/filex/common/src/fxe_file_best_effort_allocate.c \
Middlewares/ST/filex/common/src/fxe_file_close.c \
Middlewares/ST/filex/common/src/fxe_file_create.c \
Middlewares/ST/filex/common/src/fxe_file_date_time_set.c \
Middlewares/ST/filex/common/src/fxe_file_delete.c \
Middlewares/ST/filex/common/src/fxe_file_extended_allocate.c \
Middlewares/ST/filex/common/src/fxe_file_extended_best_effort_allocate.c \
Middlewares/ST/filex/common/src/fxe_file_extended_relative_seek.c \
Middlewares/ST/filex/common/src/fxe_file_extended_seek.c \
Middlewares/ST/filex/common/src/fxe_file_extended_truncate.c \
Middlewares/ST/filex/common/src/fxe_file_extended_truncate_release.c \
Middlewares/ST/filex/common/src/fxe_file_open.c \
Middlewares/ST/filex/common/src/fxe_file_read.c \
Middlewares/ST/filex/common/src/fxe_file_relative_seek.c \
Middlewares/ST/filex/common/src/fxe_file_rename.c \
Middlewares/ST/filex/common/src/fxe_file_seek.c \
Middlewares/ST/filex/common/src/fxe_file_truncate.c \
Middlewares/ST/filex/common/src/fxe_file_truncate_release.c \
Middlewares/ST/filex/common/src/fxe_file_write.c \
Middlewares/ST/filex/common/src/fxe_file_write_notify_set.c \
Middlewares/ST/filex/common/src/fxe_media_abort.c \
Middlewares/ST/filex/common/src/fxe_media_cache_invalidate.c \
Middlewares/ST/filex/common/src/fxe_media_check.c \
Middlewares/ST/filex/common/src/fxe_media_close.c \
Middlewares/ST/filex/common/src/fxe_media_close_notify_set.c \
Middlewares/ST/filex/common/src/fxe_media_exFAT_format.c \
Middlewares/ST/filex/common/src/fxe_media_extended_space_available.c \
Middlewares/ST/filex/common/src/fxe_media_flush.c \
Middlewares/ST/filex/common/src/fxe_media_format.c \
Middlewares/ST/filex/common/src/fxe_media_open.c \
Middlewares/ST/filex/common/src/fxe_media_open_notify_set.c \
Middlewares/ST/filex/common/src/fxe_media_read.c \
Middlewares/ST/filex/common/src/fxe_media_space_available.c \
Middlewares/ST/filex/common/src/fxe_media_volume_get.c \
Middlewares/ST/filex/common/src/fxe_media_volume_get_extended.c \
Middlewares/ST/filex/common/src/fxe_media_volume_set.c \
Middlewares/ST/filex/common/src/fxe_media_write.c \
Middlewares/ST/filex/common/src/fxe_system_date_get.c \
Middlewares/ST/filex/common/src/fxe_system_date_set.c \
Middlewares/ST/filex/common/src/fxe_system_time_get.c \
Middlewares/ST/filex/common/src/fxe_system_time_set.c \
Middlewares/ST/filex/common/src/fxe_unicode_directory_create.c \
Middlewares/ST/filex/common/src/fxe_unicode_directory_rename.c \
Middlewares/ST/filex/common/src/fxe_unicode_file_create.c \
Middlewares/ST/filex/common/src/fxe_unicode_file_rename.c \
Middlewares/ST/filex/common/src/fxe_unicode_name_get.c \
Middlewares/ST/filex/common/src/fxe_unicode_name_get_extended.c \
Middlewares/ST/filex/common/src/fxe_unicode_short_name_get.c \
Middlewares/ST/filex/common/src/fxe_unicode_short_name_get_extended.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_activate.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_cbw_initialize.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_configure.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_deactivate.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_device_initialize.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_device_reset.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_device_support_check.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_driver_entry.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_endpoints_get.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_entry.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_max_lun_get.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_capacity_get.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_characteristics_get.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_format_capacity_get.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_mount.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_open.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_protection_check.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_read.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_recovery_sense_get.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_media_write.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_partition_read.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_request_sense.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_sense_code_translate.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_start_stop.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_thread_entry.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_transport.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_transport_bo.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_transport_cb.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_transport_cbi.c \
Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_storage_unit_ready_test.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_bandwidth_check.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_bandwidth_claim.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_bandwidth_release.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_call.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_device_scan.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_get.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_instance_create.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_instance_destroy.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_instance_get.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_instance_verify.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_interface_scan.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_register.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_class_unregister.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_descriptor_parse.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_enumerate.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_instance_create.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_instance_delete.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_interface_get.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_interface_scan.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_set.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_delay_ms.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_address_set.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_activate.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_deactivate.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_get.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_reset.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_select.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_descriptor_read.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_get.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_remove.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_resources_free.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_device_string_get.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_endpoint_instance_create.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_endpoint_instance_delete.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_endpoint_reset.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_endpoint_transfer_abort.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_enum_thread_entry.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_hcd_register.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_hcd_thread_entry.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_hcd_transfer_request.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_hcd_unregister.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_hnp_polling_thread_entry.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_initialize.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_endpoint_get.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_instance_create.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_instance_delete.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_set.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_setting_select.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_interfaces_scan.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_new_configuration_create.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_new_device_create.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_new_device_get.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_new_endpoint_create.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_new_interface_create.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_rh_change_process.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_rh_device_extraction.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_rh_device_insertion.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_role_swap.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_tasks_run.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_transfer_request.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_transfer_request_abort.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_transfer_run.c \
Middlewares/ST/usbx/common/core/src/ux_host_stack_uninitialize.c \
Middlewares/ST/usbx/common/core/src/ux_utility_debug_callback_register.c \
Middlewares/ST/usbx/common/core/src/ux_utility_debug_log.c \
Middlewares/ST/usbx/common/core/src/ux_utility_delay_ms.c \
Middlewares/ST/usbx/common/core/src/ux_utility_descriptor_pack.c \
Middlewares/ST/usbx/common/core/src/ux_utility_descriptor_parse.c \
Middlewares/ST/usbx/common/core/src/ux_utility_error_callback_register.c \
Middlewares/ST/usbx/common/core/src/ux_utility_event_flags_create.c \
Middlewares/ST/usbx/common/core/src/ux_utility_event_flags_delete.c \
Middlewares/ST/usbx/common/core/src/ux_utility_event_flags_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_event_flags_set.c \
Middlewares/ST/usbx/common/core/src/ux_utility_long_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_long_get_big_endian.c \
Middlewares/ST/usbx/common/core/src/ux_utility_long_put.c \
Middlewares/ST/usbx/common/core/src/ux_utility_long_put_big_endian.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_add_safe.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_mulc_safe.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_mulv_safe.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_compare.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_copy.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_free.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_free_block_best_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_set.c \
Middlewares/ST/usbx/common/core/src/ux_utility_mutex_create.c \
Middlewares/ST/usbx/common/core/src/ux_utility_mutex_delete.c \
Middlewares/ST/usbx/common/core/src/ux_utility_mutex_off.c \
Middlewares/ST/usbx/common/core/src/ux_utility_mutex_on.c \
Middlewares/ST/usbx/common/core/src/ux_utility_pci_class_scan.c \
Middlewares/ST/usbx/common/core/src/ux_utility_pci_read.c \
Middlewares/ST/usbx/common/core/src/ux_utility_pci_write.c \
Middlewares/ST/usbx/common/core/src/ux_utility_physical_address.c \
Middlewares/ST/usbx/common/core/src/ux_utility_semaphore_create.c \
Middlewares/ST/usbx/common/core/src/ux_utility_semaphore_delete.c \
Middlewares/ST/usbx/common/core/src/ux_utility_semaphore_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_semaphore_put.c \
Middlewares/ST/usbx/common/core/src/ux_utility_set_interrupt_handler.c \
Middlewares/ST/usbx/common/core/src/ux_utility_short_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_short_get_big_endian.c \
Middlewares/ST/usbx/common/core/src/ux_utility_short_put.c \
Middlewares/ST/usbx/common/core/src/ux_utility_short_put_big_endian.c \
Middlewares/ST/usbx/common/core/src/ux_utility_string_length_check.c \
Middlewares/ST/usbx/common/core/src/ux_utility_string_length_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_string_to_unicode.c \
Middlewares/ST/usbx/common/core/src/ux_utility_thread_create.c \
Middlewares/ST/usbx/common/core/src/ux_utility_thread_delete.c \
Middlewares/ST/usbx/common/core/src/ux_utility_thread_identify.c \
Middlewares/ST/usbx/common/core/src/ux_utility_thread_relinquish.c \
Middlewares/ST/usbx/common/core/src/ux_utility_thread_resume.c \
Middlewares/ST/usbx/common/core/src/ux_utility_thread_schedule_other.c \
Middlewares/ST/usbx/common/core/src/ux_utility_thread_sleep.c \
Middlewares/ST/usbx/common/core/src/ux_utility_thread_suspend.c \
Middlewares/ST/usbx/common/core/src/ux_utility_timer_create.c \
Middlewares/ST/usbx/common/core/src/ux_utility_timer_delete.c \
Middlewares/ST/usbx/common/core/src/ux_utility_unicode_to_string.c \
Middlewares/ST/usbx/common/core/src/ux_utility_virtual_address.c \
Middlewares/ST/usbx/common/core/src/ux_system_error_handler.c \
Middlewares/ST/usbx/common/core/src/ux_system_initialize.c \
Middlewares/ST/usbx/common/core/src/ux_system_uninitialize.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_callback.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_controller_disable.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_ed_obtain.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_endpoint_create.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_endpoint_destroy.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_endpoint_reset.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_entry.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_frame_number_get.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_initialize.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_interrupt_handler.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_least_traffic_list_get.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_periodic_schedule.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_disable.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_enable.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_reset.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_resume.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_status_get.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_suspend.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_power_down_port.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_power_on_port.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_bulk_transfer.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_control_transfer.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_transfer.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_trans_finish.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_trans_prepare.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_transfer_abort.c \
Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_periodic_transfer.c \
Middlewares/ST/threadx/common/src/tx_initialize_high_level.c \
Middlewares/ST/threadx/common/src/tx_initialize_kernel_enter.c \
Middlewares/ST/threadx/common/src/tx_initialize_kernel_setup.c \
Middlewares/ST/threadx/common/src/tx_block_allocate.c \
Middlewares/ST/threadx/common/src/tx_block_pool_cleanup.c \
Middlewares/ST/threadx/common/src/tx_block_pool_create.c \
Middlewares/ST/threadx/common/src/tx_block_pool_delete.c \
Middlewares/ST/threadx/common/src/tx_block_pool_info_get.c \
Middlewares/ST/threadx/common/src/tx_block_pool_initialize.c \
Middlewares/ST/threadx/common/src/tx_block_pool_prioritize.c \
Middlewares/ST/threadx/common/src/tx_block_release.c \
Middlewares/ST/threadx/common/src/tx_byte_allocate.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_cleanup.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_create.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_delete.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_info_get.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_initialize.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_prioritize.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_search.c \
Middlewares/ST/threadx/common/src/tx_byte_release.c \
Middlewares/ST/threadx/common/src/tx_event_flags_cleanup.c \
Middlewares/ST/threadx/common/src/tx_event_flags_create.c \
Middlewares/ST/threadx/common/src/tx_event_flags_delete.c \
Middlewares/ST/threadx/common/src/tx_event_flags_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_info_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_initialize.c \
Middlewares/ST/threadx/common/src/tx_event_flags_set.c \
Middlewares/ST/threadx/common/src/tx_event_flags_set_notify.c \
Middlewares/ST/threadx/common/src/tx_mutex_cleanup.c \
Middlewares/ST/threadx/common/src/tx_mutex_create.c \
Middlewares/ST/threadx/common/src/tx_mutex_delete.c \
Middlewares/ST/threadx/common/src/tx_mutex_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_info_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_initialize.c \
Middlewares/ST/threadx/common/src/tx_mutex_prioritize.c \
Middlewares/ST/threadx/common/src/tx_mutex_priority_change.c \
Middlewares/ST/threadx/common/src/tx_mutex_put.c \
Middlewares/ST/threadx/common/src/tx_queue_cleanup.c \
Middlewares/ST/threadx/common/src/tx_queue_create.c \
Middlewares/ST/threadx/common/src/tx_queue_delete.c \
Middlewares/ST/threadx/common/src/tx_queue_flush.c \
Middlewares/ST/threadx/common/src/tx_queue_front_send.c \
Middlewares/ST/threadx/common/src/tx_queue_info_get.c \
Middlewares/ST/threadx/common/src/tx_queue_initialize.c \
Middlewares/ST/threadx/common/src/tx_queue_prioritize.c \
Middlewares/ST/threadx/common/src/tx_queue_receive.c \
Middlewares/ST/threadx/common/src/tx_queue_send.c \
Middlewares/ST/threadx/common/src/tx_queue_send_notify.c \
Middlewares/ST/threadx/common/src/tx_semaphore_ceiling_put.c \
Middlewares/ST/threadx/common/src/tx_semaphore_cleanup.c \
Middlewares/ST/threadx/common/src/tx_semaphore_create.c \
Middlewares/ST/threadx/common/src/tx_semaphore_delete.c \
Middlewares/ST/threadx/common/src/tx_semaphore_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_info_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_initialize.c \
Middlewares/ST/threadx/common/src/tx_semaphore_prioritize.c \
Middlewares/ST/threadx/common/src/tx_semaphore_put.c \
Middlewares/ST/threadx/common/src/tx_semaphore_put_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_create.c \
Middlewares/ST/threadx/common/src/tx_thread_delete.c \
Middlewares/ST/threadx/common/src/tx_thread_entry_exit_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_identify.c \
Middlewares/ST/threadx/common/src/tx_thread_info_get.c \
Middlewares/ST/threadx/common/src/tx_thread_initialize.c \
Middlewares/ST/threadx/common/src/tx_thread_preemption_change.c \
Middlewares/ST/threadx/common/src/tx_thread_priority_change.c \
Middlewares/ST/threadx/common/src/tx_thread_relinquish.c \
Middlewares/ST/threadx/common/src/tx_thread_reset.c \
Middlewares/ST/threadx/common/src/tx_thread_resume.c \
Middlewares/ST/threadx/common/src/tx_thread_shell_entry.c \
Middlewares/ST/threadx/common/src/tx_thread_sleep.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_analyze.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_error_handler.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_error_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_suspend.c \
Middlewares/ST/threadx/common/src/tx_thread_system_preempt_check.c \
Middlewares/ST/threadx/common/src/tx_thread_system_resume.c \
Middlewares/ST/threadx/common/src/tx_thread_system_suspend.c \
Middlewares/ST/threadx/common/src/tx_thread_terminate.c \
Middlewares/ST/threadx/common/src/tx_thread_time_slice.c \
Middlewares/ST/threadx/common/src/tx_thread_time_slice_change.c \
Middlewares/ST/threadx/common/src/tx_thread_timeout.c \
Middlewares/ST/threadx/common/src/tx_thread_wait_abort.c \
Middlewares/ST/threadx/common/src/tx_time_get.c \
Middlewares/ST/threadx/common/src/tx_time_set.c \
Middlewares/ST/threadx/common/src/txe_block_allocate.c \
Middlewares/ST/threadx/common/src/txe_block_pool_create.c \
Middlewares/ST/threadx/common/src/txe_block_pool_delete.c \
Middlewares/ST/threadx/common/src/txe_block_pool_info_get.c \
Middlewares/ST/threadx/common/src/txe_block_pool_prioritize.c \
Middlewares/ST/threadx/common/src/txe_block_release.c \
Middlewares/ST/threadx/common/src/txe_byte_allocate.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_create.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_delete.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_info_get.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_prioritize.c \
Middlewares/ST/threadx/common/src/txe_byte_release.c \
Middlewares/ST/threadx/common/src/txe_event_flags_create.c \
Middlewares/ST/threadx/common/src/txe_event_flags_delete.c \
Middlewares/ST/threadx/common/src/txe_event_flags_get.c \
Middlewares/ST/threadx/common/src/txe_event_flags_info_get.c \
Middlewares/ST/threadx/common/src/txe_event_flags_set.c \
Middlewares/ST/threadx/common/src/txe_event_flags_set_notify.c \
Middlewares/ST/threadx/common/src/txe_mutex_create.c \
Middlewares/ST/threadx/common/src/txe_mutex_delete.c \
Middlewares/ST/threadx/common/src/txe_mutex_get.c \
Middlewares/ST/threadx/common/src/txe_mutex_info_get.c \
Middlewares/ST/threadx/common/src/txe_mutex_prioritize.c \
Middlewares/ST/threadx/common/src/txe_mutex_put.c \
Middlewares/ST/threadx/common/src/txe_queue_create.c \
Middlewares/ST/threadx/common/src/txe_queue_delete.c \
Middlewares/ST/threadx/common/src/txe_queue_flush.c \
Middlewares/ST/threadx/common/src/txe_queue_front_send.c \
Middlewares/ST/threadx/common/src/txe_queue_info_get.c \
Middlewares/ST/threadx/common/src/txe_queue_prioritize.c \
Middlewares/ST/threadx/common/src/txe_queue_receive.c \
Middlewares/ST/threadx/common/src/txe_queue_send.c \
Middlewares/ST/threadx/common/src/txe_queue_send_notify.c \
Middlewares/ST/threadx/common/src/txe_semaphore_ceiling_put.c \
Middlewares/ST/threadx/common/src/txe_semaphore_create.c \
Middlewares/ST/threadx/common/src/txe_semaphore_delete.c \
Middlewares/ST/threadx/common/src/txe_semaphore_get.c \
Middlewares/ST/threadx/common/src/txe_semaphore_info_get.c \
Middlewares/ST/threadx/common/src/txe_semaphore_prioritize.c \
Middlewares/ST/threadx/common/src/txe_semaphore_put.c \
Middlewares/ST/threadx/common/src/txe_semaphore_put_notify.c \
Middlewares/ST/threadx/common/src/txe_thread_create.c \
Middlewares/ST/threadx/common/src/txe_thread_delete.c \
Middlewares/ST/threadx/common/src/txe_thread_entry_exit_notify.c \
Middlewares/ST/threadx/common/src/txe_thread_info_get.c \
Middlewares/ST/threadx/common/src/txe_thread_preemption_change.c \
Middlewares/ST/threadx/common/src/txe_thread_priority_change.c \
Middlewares/ST/threadx/common/src/txe_thread_relinquish.c \
Middlewares/ST/threadx/common/src/txe_thread_reset.c \
Middlewares/ST/threadx/common/src/txe_thread_resume.c \
Middlewares/ST/threadx/common/src/txe_thread_suspend.c \
Middlewares/ST/threadx/common/src/txe_thread_terminate.c \
Middlewares/ST/threadx/common/src/txe_thread_time_slice_change.c \
Middlewares/ST/threadx/common/src/txe_thread_wait_abort.c \
Middlewares/ST/threadx/common/src/tx_timer_activate.c \
Middlewares/ST/threadx/common/src/tx_timer_change.c \
Middlewares/ST/threadx/common/src/tx_timer_create.c \
Middlewares/ST/threadx/common/src/tx_timer_deactivate.c \
Middlewares/ST/threadx/common/src/tx_timer_delete.c \
Middlewares/ST/threadx/common/src/tx_timer_expiration_process.c \
Middlewares/ST/threadx/common/src/tx_timer_info_get.c \
Middlewares/ST/threadx/common/src/tx_timer_initialize.c \
Middlewares/ST/threadx/common/src/tx_timer_system_activate.c \
Middlewares/ST/threadx/common/src/tx_timer_system_deactivate.c \
Middlewares/ST/threadx/common/src/tx_timer_thread_entry.c \
Middlewares/ST/threadx/common/src/txe_timer_activate.c \
Middlewares/ST/threadx/common/src/txe_timer_change.c \
Middlewares/ST/threadx/common/src/txe_timer_create.c \
Middlewares/ST/threadx/common/src/txe_timer_deactivate.c \
Middlewares/ST/threadx/common/src/txe_timer_delete.c \
Middlewares/ST/threadx/common/src/txe_timer_info_get.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c  

# ASM sources
ASM_SOURCES =  \
startup_stm32l4r5xx.s

# ASM sources
ASMM_SOURCES =  \
Core/Src/tx_initialize_low_level.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_context_restore.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_context_save.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_interrupt_control.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_interrupt_disable.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_interrupt_restore.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_schedule.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_stack_build.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_system_return.S \
Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_timer_interrupt.S


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DTX_INCLUDE_USER_DEFINE_FILE \
-DFX_INCLUDE_USER_DEFINE_FILE \
-DUX_INCLUDE_USER_DEFINE_FILE \
-DUSE_HAL_DRIVER \
-DSTM32L4R5xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IAZURE_RTOS/App \
-IFileX/App \
-IUSBX/App \
-IUSBX/Target \
-IDrivers/STM32L4xx_HAL_Driver/Inc \
-IDrivers/STM32L4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32L4xx/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/ST/filex/common/inc/ \
-IMiddlewares/ST/filex/ports/generic/inc/ \
-IMiddlewares/ST/usbx/common/usbx_host_classes/inc/ \
-IMiddlewares/ST/usbx/common/core/inc/ \
-IMiddlewares/ST/usbx/ports/generic/inc/ \
-IMiddlewares/ST/usbx/common/usbx_stm32_host_controllers/ \
-IMiddlewares/ST/threadx/common/inc/ \
-IMiddlewares/ST/threadx/ports/cortex_m4/gnu/inc/


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L4R5ZITx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rd /s /q $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***